// krate-plugin-demo-go is a community plugin written in Go.
//
// A Go plugin is a standalone Go program (its own main package and go.mod) that
// calls plug.Serve with the hooks it implements. Krate launches it as a
// subprocess over HashiCorp go-plugin (net/rpc), keeps it alive across dev
// hot-reloads, and kills it on build/serve teardown.
//
// The plugin author ships per-platform binaries. The simplest distribution is
// an npm package whose index.js exposes a tiny descriptor factory (runtime +
// binaries) pointing at prebuilt binaries included in the package.
//
// This example, when built to a per-platform binary, can be wired into
// krate.config.ts with:
//
//	import demoGoPlugin from 'krate-plugin-demo-go';
//	export default { plugins: [demoGoPlugin({ greeting: 'Hi' })] };
package main

import (
	"strings"

	"github.com/kratejs/krate/packages/compiler/ast"
	"github.com/kratejs/krate/packages/compiler/pluginsdk"
)

const demoCSS = ".demo-banner-go{background:#0f766e;color:white;padding:8px 16px;text-align:center;font-weight:600;}"

func editFirstJSXText(prog *ast.Program, greeting string) {
	if len(prog.Body) == 0 {
		return
	}
	exp, ok := prog.Body[0].(*ast.ExportStmt)
	if !ok {
		return
	}
	fn, ok := exp.Declaration.(*ast.FnDecl)
	if !ok {
		return
	}
	if len(fn.Body) == 0 {
		return
	}
	ret, ok := fn.Body[0].(*ast.ReturnStmt)
	if !ok {
		return
	}
	jsx, ok := ret.Value.(*ast.JSXElement)
	if !ok {
		return
	}
	for _, child := range jsx.Children {
		if text, ok := child.(*ast.JSXText); ok {
			text.Value = strings.ReplaceAll(text.Value, "GO-PLUGIN", greeting)
		}
	}
}

func main() {
	plug.Serve("krate-plugin-demo-go", plug.Hooks{BeforeBuild: func(ctx *plug.BuildArgs) error {
		// The richer context carries the project layout; EmitFile appends to the
		// output files just like assigning to ctx.Files.
		ctx.EmitFile("demo-go-notice.txt",
			"Generated by krate-plugin-demo-go (BeforeBuild)\n"+
				"Root: "+ctx.Root+"\n"+
				"Pages dir: "+ctx.PagesDir+"\n"+
				"Version: "+ctx.Version+"\n")
		return nil
	},
		AfterParse: func(ctx *plug.ParseArgs) error {
			editFirstJSXText(ctx.Program, "Hello from the Go Demo Plugin!")
			return nil
		},
		AfterRender: func(ctx *plug.RenderArgs) error {
			// SDK helpers mirror the JS krate.injectHead / krate.injectCSS.
			ctx.InjectHead("\n<meta name=\"generator\" content=\"krate-plugin-demo-go\">")
			ctx.MetaTags = append(ctx.MetaTags, `name="demo-go" content="true"`)
			ctx.InjectCSS(demoCSS)
			ctx.HTML = `<div class="demo-banner-go">Served by the Go plugin</div>` + ctx.HTML
			return nil
		},
		ServeRequest: func(ctx *plug.ServeRequestArgs) error {
			if ctx.Path == "/__demo-go" {
				ctx.Action = "respond"
				ctx.Status = 200
				ctx.Body = "hello from the Go plugin"
				ctx.Headers = map[string]string{"content-type": "text/plain"}
			}
			return nil
		},
		ServeResponse: func(ctx *plug.ServeResponseArgs) error {
			ctx.Body = ctx.Body + "\n<!-- served-by-demo-go -->"
			if ctx.Headers == nil {
				ctx.Headers = map[string]string{}
			}
			ctx.Headers["x-demo-go"] = "1"
			return nil
		},
	})
}
